# Configuración del Sistema de Monitoreo Forestal
# Madre de Dios, Perú

# Directorio de datos
data:
  root_dir: "data"
  raster_dir: "data/rasters"
  vector_dir: "data/vectors"
  models_dir: "models"
  output_dir: "outputs"

# Configuración del área de estudio
study_area:
  name: "Madre de Dios"
  country: "Perú"
  center_lat: -12.5
  center_lon: -70.0
  zoom_level: 7
  bbox:  # Bounding box [minx, miny, maxx, maxy]
    - -71.5
    - -13.5
    - -68.5
    - -11.5

# Archivos de entrada
input_files:
  vv_backscatter: "vv_backscatter.tif"
  vh_backscatter: "vh_backscatter.tif"
  vh_vv_ratio: "vh_vv_ratio.tif"
  cusum: "rsum_max_cusum.tif"
  classification: "class_map.tif"
  alerts: "alerts.geojson"

# Configuración de visualización
visualization:
  default_opacity: 0.6
  tile_provider: "OpenStreetMap"
  satellite_tiles: "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"
  
  # Colormaps para cada capa
  colormaps:
    vv:
      colors: ["#000080", "#4169E1", "#87CEEB"]
      name: "VV Backscatter"
    vh:
      colors: ["#2F4F4F", "#20B2AA", "#AFEEEE"]
      name: "VH Backscatter"
    ratio:
      colors: ["#8B4513", "#DAA520", "#FFD700"]
      name: "VH/VV Ratio"
    cusum:
      colors: ["#006400", "#FFFF00", "#FF4500"]
      name: "CuSum"
    classification:
      colors: ["#228B22", "#ADFF2F", "#FFD700", "#FF8C00", "#FF0000"]
      name: "Classification"
      labels:
        0: "Bosque Intacto"
        1: "Bosque Secundario"
        2: "Degradación Leve"
        3: "Degradación Severa"
        4: "Deforestación"

# Configuración del modelo Random Forest
random_forest:
  n_estimators: 500
  max_depth: 20
  min_samples_split: 10
  min_samples_leaf: 5
  max_features: "sqrt"
  random_state: 42
  test_size: 0.2

# Configuración U-TAE
utae:
  model_path: "models/utae_weights.pth"
  input_channels: 2  # VV, VH
  num_classes: 5
  tile_size: 256
  temporal_length: 24  # 24 imágenes (2 años)

# Procesamiento SAR
sar_processing:
  speckle_filter:
    enabled: true
    window_size: 5
  
  cusum_params:
    threshold: 0.5
    min_change_duration: 3  # meses
  
  glcm_params:
    distances: [1, 2]
    angles: [0, 45, 90, 135]  # grados

# Casos de estudio
case_studies:
  - name: "Caso 1: Minería Ilegal - Río Malinowski"
    coords: [-12.8, -70.2]
    zoom: 12
    area_ha: 450
    period: "2020-2024"
    severity: "high"
    
  - name: "Caso 2: Tala Selectiva - Reserva Tambopata"
    coords: [-12.3, -69.5]
    zoom: 12
    area_ha: 1200
    period: "2021-2024"
    severity: "medium"
    
  - name: "Caso 3: Carretera Interoceánica - Zona de Amortiguamiento"
    coords: [-12.6, -69.8]
    zoom: 11
    area_ha: 2800
    period: "2019-2024"
    severity: "medium"

# Umbrales de alerta
alert_thresholds:
  degradation_mild: 2.0    # CuSum threshold
  degradation_severe: 5.0
  deforestation: 8.0
  
  # Área mínima para generar alerta (hectáreas)
  min_area: 10

# Configuración de exportación
export:
  formats:
    - geojson
    - png
    - geotiff
  
  geojson:
    crs: "EPSG:4326"
    precision: 6
  
  png:
    dpi: 300
    width: 1920
    height: 1080
  
  geotiff:
    compress: "lzw"
    tiled: true
    blocksize: 256

# Configuración Streamlit
streamlit:
  page_title: "Forest Degradation Monitor - Madre de Dios"
  page_icon: "🛰️"
  layout: "wide"
  initial_sidebar_state: "expanded"
  
  theme:
    primary_color: "#FC3D21"      # Rojo NASA
    background_color: "#0B3D91"   # Azul NASA
    secondary_background: "#2C5F8D"
    text_color: "#FFFFFF"

# Logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/forest_monitor.log"

# Performance
performance:
  max_raster_size_mb: 500
  downscale_factor: 1.0  # 1.0 = sin reducción, 0.5 = mitad de resolución
  cache_enabled: true
  parallel_processing: true
  num_workers: -1  # -1 = usar todos los cores

# Metadatos
metadata:
  version: "1.0.0"
  last_update: "2024-09-28"
  data_source: "Sentinel-1 (ESA Copernicus)"
  contact: "forestmonitor@example.com"
  repository: "https://github.com/tu-usuario/forest-degradation-monitor"
